
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  host: localhost
  port: 5432
  user: user
  password: user

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app
